# main menu navigation
menu:
  ä¸»é¡µ: /
  åšå®¢: /posts
  åˆ†ç±»: /archives
  # ä½“ç³»: /knowledge
  # é¡¹ç›®: /project
  # å…³äº: /about
  å‹é“¾: /friend
  ç•™è¨€: /message
  è¯´è¯´: /saysay
  å¼€å¾€: https://travellings.now.sh/

site_name: Sorryfu #ç½‘ç«™çš„åç§°
author: Sorryfu  #æ–‡ç« çš„é»˜è®¤ä½œè€…
icon: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #æ ‡ç­¾é¡µå›¾æ ‡

#è‡ªæˆ‘ä»‹ç»
intro:
  title: Introduction
  sub: Sorryfuï¼Œå¤§ä¸‰åœ¨è¯»ï¼ŒJavaä¸æ™ºèƒ½è®¾å¤‡å¼€å‘æ–¹å‘ï¼Œå–œæ¬¢é‡‘åº¸çš„å°è¯´ï¼Œè¿™æ˜¯æˆ‘çš„ä¸ªäººåšå®¢ï¼Œæ¬¢è¿å‚è§‚ğŸ˜˜
  img: https://cdn.jsdelivr.net/gh/fushaolei/img/20200624215641.jpg

#è”ç³»æ–¹å¼  æ›´å¤šå›¾æ ‡ï¼šhttps://remixicon.com/
contact:
  Email: 
    - mailto:1563250958@qq.com
    - ri-mail-line
  Github:
    - https://github.com/FuShaoLei
    - ri-github-line

#å‹é“¾
link:
  BlogWe: https://blogwe.com/
  åŸå—ç ´äº‹: https://www.ronce.cc/
  ç«¹é’è™«ã®çª: https://1940879828.github.io/
  CtrlCVåšå®¢: https://www.hack-er.cn/
  ä¸¤å°æ— çŒœ: https://www.cnblogs.com/charlottepl/
  ç­–ç­–çš„å°é»‘å±‹: https://www.cnblogs.com/occlive/
  Guan FuQing: https://yiki.tech
  é˜¿ç‘: https://wenzia.com
  ä¾å°˜: https://yichen.online

# Valineè¯„è®ºç³»ç»Ÿ
valine:
  open: true # true | false æ˜¯å¦æ‰“å¼€ï¼Œé»˜è®¤false
  appid: HBismw2vU6hg56PslAF2APW1-gzGzoHsz  #Leancloudåº”ç”¨çš„AppID
  appkey: k41e2BJYdNbojyHuMnKT5LBK  #Leancloudåº”ç”¨çš„AppKey
  verify: false #éªŒè¯ç 
  notify: true #è¯„è®ºå›å¤æé†’
  avatar: robohash #è¯„è®ºåˆ—è¡¨å¤´åƒæ ·å¼ï¼š''/mm/identicon/monsterid/wavatar/retro/hide
  #å¤´åƒç±»å‹å¯è§ï¼š https://valine.js.org/avatar.html
  placeholder: ç•™ä¸‹ä½ æ¥è¿‡çš„ç—•è¿¹~ #è¯„è®ºæ¡†å ä½ç¬¦

plugins:
  # ä»£ç é«˜äº®
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/vs2015.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles