########## å…³äºä¸»é¡µçš„è®¾ç½® ##########

## TODO å¾…æ¸…é™¤

# homeé¡µå¯é€‰ç±»å‹
home:
  type: "simple" # ä¸»é¡µçš„ç±»å‹ï¼Œå¯é€‰ home | img | simple

# archiveé¡µå¯é€‰ç±»å‹
archive:
  type: "simple" # archiveçš„ç±»å‹ï¼Œå¯é€‰ img | simple


archive_img_mode: # TODO è¿™é‡Œéœ€è¦æ”¹ï¼Œä¸åº”è¯¥ç”¨è¿™ç§å›¾ç‰‡ï¼Œåº”è¯¥æ”¹æˆæœ¬åœ°çš„å›¾ç‰‡
  default_cover: #é»˜è®¤çš„cover
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/01.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/02.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/03.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/04.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/05.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/06.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/07.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/08.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/09.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/10.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/11.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/12.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/13.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/14.jpg
    - https://cdn.jsdelivr.net/gh/fushaolei/cdn-white@1.0/cover/15.jpg

# icon
icon: favicon.ico
# header
site_name: white
site_description: A minimalist theme for hexo.

menu:
  é¦–é¡µ: /
  é¡µé¢: /page


## æœ¬åœ°æœç´¢ TODO å¾…å¤„ç†
search:
  open: false # æ˜¯å¦å¼€å¯
  page: /search # é¡µé¢è·¯å¾„ï¼ˆé€šå¸¸å‘½åä¸ºsearchï¼‰

# è‡ªæˆ‘ä»‹ç»
intro:
  title: ğŸ‘‹ Hello
  sub: 'A [White](https://github.com/FuShaoLei/hexo-theme-white) theme for [Hexo](http://hexo.io/)' # æ”¯æŒmarkdown
  avator: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #å¤´åƒ
  author: fushaolei # æ‰€æœ‰æ–‡ç« çš„é»˜è®¤ä½œè€…

# contact
# more icon: https://remixicon.com/
contact:
  Github:
    - https://github.com/FuShaoLei/hexo-theme-white
    - ri-github-line
  Email:
    - mailto:1563250958@qq.com
    - ri-mail-line
  Music:
    - https://music.163.com/
    - ri-netease-cloud-music-line
  Bilibili:
    - https://bilibili.com/
    - ri-bilibili-line
  Youtube:
    - https://youtube.com/
    - ri-youtube-line


# comment
comments:
  open: false
  system: cusdis # é€‰æ‹©è¯„è®ºç³»ç»Ÿ å¯é€‰ valine,gitalk,livere,cusdis
  # Valine
  valine:
    appid: # Leancloudåº”ç”¨çš„AppID  è¿™é‡Œå’Œä¸‹é¢çš„è¦æ¢æˆä½ è‡ªå·±çš„å•ŠQAQ
    appkey: # Leancloudåº”ç”¨çš„AppKey
    verify: false # éªŒè¯ç 
    notify: true # è¯„è®ºå›å¤æé†’
    avatar: robohash # è¯„è®ºåˆ—è¡¨å¤´åƒæ ·å¼ï¼š''/mm/identicon/monsterid/wavatar/retro/hide
    # å¤´åƒç±»å‹å¯è§ï¼š https://valine.js.org/avatar.html
    placeholder: ç•™ä¸‹ä½ æ¥è¿‡çš„ç—•è¿¹~ #è¯„è®ºæ¡†å ä½ç¬¦
  # Gitalk
  gitalk:
    owner:  # Github ç”¨æˆ·å,
    repo:  # å‚¨å­˜è¯„è®ºissueçš„githubä»“åº“å
    admin:  # Github ç”¨æˆ·å
    clientID:  # Github Application clientID
    clientSecret: # Github Application clientSecret
  # livere
  livere: # å‰å¾€ http://livere.com/ ç”³è¯·è´¦å·
    dataId: city #å…è´¹ç‰ˆæœ¬city
    dataUid: #å®‰è£…ä»£ç ä¸­ data-uid åé¢æ•°æ®
  cusdis:
    app_id:

pagination: # TODO æ·»åŠ å¤šè¯­è¨€æ”¯æŒ
  prev: ä¸Šä¸€é¡µ
  next: ä¸‹ä¸€é¡µ


footer: Power by [Hexo](http://hexo.io/) Theme by [White](https://github.com/FuShaoLei/hexo-theme-white) # markdownè¯­æ³•



lazyload:
  open: true
